export const PLAYMAKER_TUTORIAL_STORAGE_KEY = 'gs_playmaker_tutorial_complete_v1';

export const PLAYMAKER_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'welcome',
    target: '[data-tutorial="workspace"]',
    eyebrow: 'CREATE A PLAY',
    title: 'Build one tactical decision at a time',
    body: 'This walkthrough teaches the complete 2D-to-3D workflow without changing your draft. You can interact with the highlighted controls or simply move through the lesson.',
    detail: 'A strong play has a readable setup, decision, and resolution.',
  },
  {
    id: 'identity',
    target: '[data-tutorial="identity"]',
    eyebrow: 'PLAY IDENTITY',
    title: 'Name the outcome, not the diagram',
    body: 'Give the play a short name and describe the tactical purpose. This copy helps teammates understand when the play applies before they study the routes.',
    detail: 'Example: Controlled entry with wide support and a late middle option.',
  },
  {
    id: 'shape',
    target: '[data-tutorial="court"]',
    eyebrow: 'STARTING SHAPE',
    title: 'Place all 12 players',
    body: 'Drag players on the vertical rink or select them and enter Width and Depth. Start with both goalies, then place pressure, the ball carrier, and support.',
    detail: 'Our net is at the bottom. Every player should shift between moments, even when the change is small.',
  },
  {
    id: 'moment',
    target: '[data-tutorial="moment"]',
    eyebrow: 'KEYFRAME',
    title: 'Make each moment teach one read',
    body: 'A moment is a complete team shape. Give it a coaching cue, duplicate it to create the next beat, and set enough travel time for the movement to remain readable.',
    detail: 'Use extra moments for a new decision or responsibility, not for every tiny movement.',
  },
  {
    id: 'player',
    target: '[data-tutorial="player"]',
    eyebrow: 'PLAYER INTENT',
    title: 'Explain why each player moves',
    body: 'Select a player, place the destination, and choose the intent that best describes the job. Intent helps the 3D replay face and animate the player coherently.',
    detail: 'Set all 12 players before judging spacing or replay readiness.',
  },
  {
    id: 'ball',
    target: '[data-tutorial="ball"]',
    eyebrow: 'BALL CONTRACT',
    title: 'Set possession, then the next decision',
    body: 'First select the carrier at this moment. If the ball is loose, drag the orange ball to its exact rink position. Then define carry, direct pass, boards pass, shot, or loose ball into the next moment.',
    detail: 'For every pass, select the exact receiver. That identity controls the 2D line and destination possession, and remains the destination in all 3D cameras. Loose-ball positions follow the same 2D-to-3D contract.',
  },
  {
    id: 'timeline',
    target: '[data-tutorial="timeline"]',
    eyebrow: 'FULL SEQUENCE',
    title: 'Review timing across every moment',
    body: 'Use the moment strip to move through the authored keyframes. Play the complete sequence, scrub problem areas, and adjust travel time where movement feels rushed.',
    detail: 'Setup, decision, and resolution should each remain on screen long enough to understand.',
  },
  {
    id: 'preview',
    target: '[data-tutorial="preview"]',
    eyebrow: 'SHARED REPLAY',
    title: 'Check the same play in 3D',
    body: 'Open Preview after the 2D sequence is coherent. Inspect Broadcast, Overhead, and Bench, then use Role to follow each exact position through its ball reads. Orbit, pan, zoom, and toggle only the coaching layers you need.',
    detail: 'The 3D view uses the same player identities and ball decisions. Confirm that the selected receiver remains the destination.',
  },
  {
    id: 'readiness',
    target: '[data-tutorial="readiness"]',
    eyebrow: 'VALIDATION',
    title: 'Resolve issues before sharing',
    body: 'Readiness checks movement for all 12 players and validates ball continuity. Fix the first reported issue, replay from the start, and confirm the final possession.',
    detail: 'Readiness confirms animation structure. It does not replace a teammate or coach reviewing the tactical decision.',
  },
  {
    id: 'save',
    target: '[data-tutorial="actions"]',
    eyebrow: 'SAVE AND SHARE',
    title: 'Keep the play portable',
    body: 'Save keeps a local library. Share copies a portable link. Export creates a play file that can be backed up or imported on another device.',
    detail: 'Accounts are optional; authoring and local sharing do not require a paid model or service.',
  },
]);
