import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('player rig validation', () => {
  it('accepts CC and Mixamo hip naming and scopes bridge checks out of strict production', () => {
    const script = readFileSync('scripts/validate-player-rig.mjs', 'utf8');

    expect(script).toContain("hasAnyNode(stats, ['Hips', 'Hip'])");
    expect(script).toContain('if (!strictProduction)');
  });

  it('requires strict production runners to carry Blender retarget report evidence', () => {
    const script = readFileSync('scripts/validate-player-rig.mjs', 'utf8');

    expect(script).toContain('blender-normalize-report.json');
    expect(script).toContain('assertRunnerRetargetReport');
    expect(script).toContain('normalMotionPosture');
    expect(script).toContain('motionSourceClips');
    expect(script).toContain('classifyRunnerMotionQuality');
    expect(script).toContain('requiredClipNames: requiredClips');
    expect(script).toContain('requireFinalGradeMotion');
    expect(script).toContain("process.argv.includes('--require-final-grade-motion') || strictProduction");
    expect(script).toContain('missing final-grade clips');
    expect(script).toContain('final-grade clips missing provenance');
    expect(script).toContain('sourceQuality');
    expect(script).toContain('usageRights');
    expect(script).toContain('retarget motion quality');
    expect(script).toContain('seed-quality clips');
    expect(script).toContain('invalid final-grade capture method');
    expect(script).toContain('final-grade clips with invalid capture methods');
    expect(script).toContain('final-grade clips with invalid retarget duration');
    expect(script).toContain('final-grade clips with invalid retarget frame count');
    expect(script).toContain('isFinalGradeRunnerSourceQuality');
    expect(script).toContain('final-grade-bvh-action-clip');
    expect(script).toContain('final-grade source is still marked as a seed handoff');
    expect(script).toContain('final-grade source is missing usage-rights metadata');
    expect(script).toContain('invalid final-grade usage rights');
    expect(script).toContain('final-grade clips with invalid usage rights');
    expect(script).toContain('sourceDurationSeconds');
    expect(script).toContain('retargetedDurationSeconds');
    expect(script).toContain('minimumRetargetedDurationSeconds');
    expect(script).toContain('sourceFrameCount');
    expect(script).toContain('retargetedFrameCount');
    expect(script).toContain('minimumRetargetedFrameCount');
    expect(script).toContain('maxUpperArmSwingDegrees');
    expect(script).toContain('maxAllowedUpperArmSwingDegrees');
    expect(script).toContain('maxUpperArmLateralDegrees');
    expect(script).toContain('maxAllowedUpperArmLateralDegrees');
    expect(script).toContain('maxUpperArmExposureDegrees');
    expect(script).toContain('maxAllowedUpperArmExposureDegrees');
    expect(script).toContain('minUpperArmDropDegrees');
    expect(script).toContain('minRequiredUpperArmDropDegrees');
    expect(script).toContain('retargetedStickActionUpperArmLateralDegrees');
    expect(script).toContain('maximumRetargetedStickActionUpperArmLateralDegrees');
    expect(script).toContain('retargetedStickActionUpperArmExposureDegrees');
    expect(script).toContain('maximumRetargetedStickActionUpperArmExposureDegrees');
    expect(script).toContain('maxForearmLiftDegrees');
    expect(script).toContain('maxAllowedForearmLiftDegrees');
    expect(script).toContain('maxHandLiftDegrees');
    expect(script).toContain('maxAllowedHandLiftDegrees');
    expect(script).toContain('normal runner upper-arm lateral exceeds guardrail');
    expect(script).toContain('normal runner upper-arm exposure exceeds guardrail');
    expect(script).toContain('normal runner forearm lift exceeds guardrail');
    expect(script).toContain('normal runner hand lift exceeds guardrail');
    expect(script).toContain('upper-arm drop is below guardrail');
    expect(script).toContain('requiredNormalMotionClips');
    expect(script).toContain('clipPostures');
    expect(script).toContain('normalMotionPosture is missing per-clip posture evidence');
    expect(script).toContain('sourceMotionMetrics');
    expect(script).toContain('rootForwardTravelUnits');
    expect(script).toContain('minimumRootForwardTravelUnits');
    expect(script).toContain('rootForwardSpeedChangeUnits');
    expect(script).toContain('minimumRootForwardSpeedChangeUnits');
    expect(script).toContain('maxFrameRotationDeltaDegrees');
    expect(script).toContain('maximumFrameRotationDeltaDegrees');
    expect(script).toContain('maxFrameRotationAccelerationDegrees');
    expect(script).toContain('maximumFrameRotationAccelerationDegrees');
    expect(script).toContain('stickActionTwoHandBalanceRatio');
    expect(script).toContain('minimumStickActionTwoHandBalanceRatio');
    expect(script).toContain('stickActionTwoHandSyncRatio');
    expect(script).toContain('minimumStickActionTwoHandSyncRatio');
    expect(script).toContain('stickActionPhaseChanges');
    expect(script).toContain('minimumStickActionPhaseChanges');
    expect(script).toContain('strideCycleSpanRatio');
    expect(script).toContain('minimumStrideCycleSpanRatio');
    expect(script).toContain('stickActionBeatSpanRatio');
    expect(script).toContain('minimumStickActionBeatSpanRatio');
    expect(script).toContain('stickActionReleasePeakRatio');
    expect(script).toContain('minimumStickActionReleasePeakRatio');
    expect(script).toContain('maximumStickActionReleasePeakRatio');
    expect(script).toContain('stickActionSupportedReleaseRatio');
    expect(script).toContain('minimumStickActionSupportedReleaseRatio');
    expect(script).toContain('stickActionTorsoRangeDegrees');
    expect(script).toContain('minimumStickActionTorsoRangeDegrees');
    expect(script).toContain('stickActionLowerBodyLeadFrames');
    expect(script).toContain('minimumStickActionLowerBodyLeadFrames');
    expect(script).toContain('stickActionRecoveryRatio');
    expect(script).toContain('minimumStickActionRecoveryRatio');
    expect(script).toContain('athleticTorsoLeanDegrees');
    expect(script).toContain('minimumAthleticTorsoLeanDegrees');
    expect(script).toContain('locomotionLoopClosureErrorDegrees');
    expect(script).toContain('rootVerticalLoopOffsetUnits');
    expect(script).toContain('rootLateralShiftUnits');
    expect(script).toContain('minimumRootLateralShiftUnits');
    expect(script).toContain('rootVerticalBounceUnits');
    expect(script).toContain('minimumRootVerticalBounceUnits');
    expect(script).toContain('retargetedRootVerticalBounceUnits');
    expect(script).toContain('minimumRetargetedRootVerticalBounceUnits');
    expect(script).toContain('retargetedReadyStanceLegLoadDegrees');
    expect(script).toContain('minimumRetargetedReadyStanceLegLoadDegrees');
    expect(script).toContain('readyStanceLegLoadDegrees');
    expect(script).toContain('minimumReadyStanceLegLoadDegrees');
    expect(script).toContain('legDriveRangeDegrees');
    expect(script).toContain('minimumLegDriveRangeDegrees');
    expect(script).toContain('retargetedLegDriveRangeDegrees');
    expect(script).toContain('minimumRetargetedLegDriveRangeDegrees');
    expect(script).toContain('retargetedLocomotionStrideBalanceRatio');
    expect(script).toContain('minimumRetargetedLocomotionStrideBalanceRatio');
    expect(script).toContain('retargetedLocomotionFootPlantDriveRatio');
    expect(script).toContain('minimumRetargetedLocomotionFootPlantDriveRatio');
    expect(script).toContain('retargetedFootPlantStabilityRatio');
    expect(script).toContain('minimumRetargetedFootPlantStabilityRatio');
    expect(script).toContain('retargetedFootPlantStrideCoverageRatio');
    expect(script).toContain('minimumRetargetedFootPlantStrideCoverageRatio');
    expect(script).toContain('retargetedFootPlantGroundedRatio');
    expect(script).toContain('minimumRetargetedFootPlantGroundedRatio');
    expect(script).toContain('retargetedFootPlantContactFrameCount');
    expect(script).toContain('minimumRetargetedFootPlantContactFrames');
    expect(script).toContain('retargetedFootPlantSideCount');
    expect(script).toContain('minimumRetargetedFootPlantSideCount');
    expect(script).toContain('retargetedFootPlantBalanceRatio');
    expect(script).toContain('minimumRetargetedFootPlantBalanceRatio');
    expect(script).toContain('retargetedFootPlantMinSideHoldFrames');
    expect(script).toContain('minimumRetargetedFootPlantHoldFramesPerSide');
    expect(script).toContain('retargetedFootPlantMaxSlideUnits');
    expect(script).toContain('maximumRetargetedFootPlantMaxSlideUnits');
    expect(script).toContain('locomotionStrideBalanceRatio');
    expect(script).toContain('minimumLocomotionStrideBalanceRatio');
    expect(script).toContain('locomotionFootPlantDriveRatio');
    expect(script).toContain('minimumLocomotionFootPlantDriveRatio');
    expect(script).toContain('retargetedStickHandRangeDegrees');
    expect(script).toContain('minimumRetargetedStickHandRangeDegrees');
    expect(script).toContain('retargetedStickActionTwoHandBalanceRatio');
    expect(script).toContain('minimumRetargetedStickActionTwoHandBalanceRatio');
    expect(script).toContain('retargetedStickActionTwoHandSyncRatio');
    expect(script).toContain('minimumRetargetedStickActionTwoHandSyncRatio');
    expect(script).toContain('retargetedStickActionTwoHandContactRatio');
    expect(script).toContain('minimumRetargetedStickActionTwoHandContactRatio');
    expect(script).toContain('retargetedStickActionTwoHandContactFrameCount');
    expect(script).toContain('minimumRetargetedStickActionTwoHandContactFrameCount');
    expect(script).toContain('retargetedStickActionLowerBodyLeadFrames');
    expect(script).toContain('minimumRetargetedStickActionLowerBodyLeadFrames');
    expect(script).toContain('retargetedStickActionRecoveryRatio');
    expect(script).toContain('minimumRetargetedStickActionRecoveryRatio');
    expect(script).toContain('retargetedStickActionPhaseChanges');
    expect(script).toContain('minimumRetargetedStickActionPhaseChanges');
    expect(script).toContain('retargetedStickActionBeatSpanRatio');
    expect(script).toContain('minimumRetargetedStickActionBeatSpanRatio');
    expect(script).toContain('retargetedStickActionReleasePeakRatio');
    expect(script).toContain('minimumRetargetedStickActionReleasePeakRatio');
    expect(script).toContain('maximumRetargetedStickActionReleasePeakRatio');
    expect(script).toContain('retargetedStickActionSupportedReleaseRatio');
    expect(script).toContain('minimumRetargetedStickActionSupportedReleaseRatio');
    expect(script).toContain('retargetedStickActionUpperArmLiftDegrees');
    expect(script).toContain('maximumRetargetedStickActionUpperArmLiftDegrees');
    expect(script).toContain('retargetedStickActionUpperArmSwingDegrees');
    expect(script).toContain('maximumRetargetedStickActionUpperArmSwingDegrees');
    expect(script).toContain('retargetedStickActionUpperArmExposureDegrees');
    expect(script).toContain('maximumRetargetedStickActionUpperArmExposureDegrees');
    expect(script).toContain('retargetedStickActionForearmLiftDegrees');
    expect(script).toContain('maximumRetargetedStickActionForearmLiftDegrees');
    expect(script).toContain('retargetedStickActionHandLiftDegrees');
    expect(script).toContain('maximumRetargetedStickActionHandLiftDegrees');
    expect(script).toContain('retargetedClipMetricMaximumKeys');
    expect(script).toContain('retargetedLocomotionArmSwingRangeDegrees');
    expect(script).toContain('minimumRetargetedLocomotionArmSwingRangeDegrees');
    expect(script).toContain('retargetedLocomotionContralateralSyncRatio');
    expect(script).toContain('minimumRetargetedLocomotionContralateralSyncRatio');
    expect(script).toContain('retargetedTorsoFollowThroughDegrees');
    expect(script).toContain('minimumRetargetedTorsoFollowThroughDegrees');
    expect(script).toContain('retargetedHipShoulderSeparationDegrees');
    expect(script).toContain('minimumRetargetedHipShoulderSeparationDegrees');
    expect(script).toContain('retargetedAthleticTorsoLeanDegrees');
    expect(script).toContain('minimumRetargetedAthleticTorsoLeanDegrees');
    expect(script).toContain('retargetedMaxFrameRotationDeltaDegrees');
    expect(script).toContain('maximumRetargetedFrameRotationDeltaDegrees');
    expect(script).toContain('retargetedMaxFrameRotationAccelerationDegrees');
    expect(script).toContain('maximumRetargetedFrameRotationAccelerationDegrees');
    expect(script).toContain('retargetedLocomotionLoopClosureErrorDegrees');
    expect(script).toContain('maximumRetargetedLoopClosureErrorDegrees');
    expect(script).toContain('retargetedRootVerticalLoopOffsetUnits');
    expect(script).toContain('maximumRetargetedLoopVerticalOffsetUnits');
    expect(script).toContain('alternatingLegSeparationDegrees');
    expect(script).toContain('minimumAlternatingLegSeparationDegrees');
    expect(script).toContain('locomotionArmSwingRangeDegrees');
    expect(script).toContain('minimumLocomotionArmSwingRangeDegrees');
    expect(script).toContain('locomotionContralateralSyncRatio');
    expect(script).toContain('minimumLocomotionContralateralSyncRatio');
    expect(script).toContain('footPlantContactFrameCount');
    expect(script).toContain('minimumFootPlantContactFrames');
    expect(script).toContain('footPlantSideCount');
    expect(script).toContain('minimumFootPlantSideCount');
    expect(script).toContain('footPlantBalanceRatio');
    expect(script).toContain('minimumFootPlantBalanceRatio');
    expect(script).toContain('footPlantMinSideHoldFrames');
    expect(script).toContain('minimumFootPlantHoldFramesPerSide');
    expect(script).toContain('maxFootPlantRootDriftUnits');
    expect(script).toContain('maximumFootPlantRootDriftUnits');
    expect(script).toContain('maximumLoopClosureErrorDegrees');
    expect(script).toContain('maximumLoopVerticalOffsetUnits');
    expect(script).toContain('missingMotionSources');
    expect(script).toContain('invalidMotionSources');
  });

  it('requires production runner equipment to be present on both body sides', () => {
    const script = readFileSync('scripts/validate-player-rig.mjs', 'utf8');

    expect(script).toContain('missingSideBalancedPartGroups');
    expect(script).toContain('requiredSideBalancedPartGroups');
    expect(script).toContain('stats.meshNames,');
    expect(script).toContain('missing ${group.missingSide}-side runner equipment');
  });

  it('fails production runners that exceed accepted real-athlete dimensions', () => {
    const script = readFileSync('scripts/validate-player-rig.mjs', 'utf8');

    expect(script).toContain('dimensions: getSceneDimensions');
    expect(script).toContain('options.maxWidth');
    expect(script).toContain('exceeds runner width guardrail');
    expect(script).toContain('options.maxDepth');
    expect(script).toContain('exceeds runner depth guardrail');
    expect(script).toContain('options.minHeight');
    expect(script).toContain('is below runner height guardrail');
    expect(script).toContain('options.maxHeight');
    expect(script).toContain('exceeds runner height guardrail');
  });
});
